### ISSUE TITLE
The output of the object category detected by onnxruntime C++ is all 0

### ISSUE THREAD

**Issue by GitHubLuGeng** [zhiqwang/yolov5-rt-stack#220]
### 🐛 Describe the bug

onnxruntime C++检测到的物体输出类型全是person
相同yolov5s  v6.0 onnx模型python demo推理正确

如下图：
![result_screenshot_29 10 2021](https://user-images.githubusercontent.com/20118852/139436397-11749a93-f275-4253-973c-c6a8f1d643c3.png)

### Versions

main

**Comment by zhiqwang** [comment]
Hi @GitHubLuGeng 

The reason for this occurs should be a bug of the type of the labels in the following, we fixed this issue in #221 . Please pull the latest code to verify that this issue is fixed correctly.

https://github.com/zhiqwang/yolov5-rt-stack/blob/b8d845d1c164d86723e79ed4ad0a288864becc12/deployment/onnxruntime/main.cpp#L150

And as such I'm closing this issue, feel free to reopen this or create a new ticket if you have more questions.
