### ISSUE TITLE
Conert inference results of c++ to bbox, class id and score

### ISSUE THREAD

**Issue by stereomatchingkiss** [zhiqwang/yolov5-rt-stack#98]
How could convert the results of 

`output.toTuple()->elements()[1];`

to bbox, score and class_idx? The deployment/src/main.cpp do not mention how to do it. Thanks

**Comment by zhiqwang** [comment]
Hi @stereomatchingkiss 

That's a great catch! These files in the deployment directory haven't beed updated for a long time (And its interface is a little outdated, we should fix these). Now, I think you can try the interface in unit-test as following:

https://github.com/zhiqwang/yolov5-rt-stack/blob/f4bb74ca14496883bf5252c9699864eba675f90d/test/tracing/test_tracing.cpp#L26-L37

And the CI is below (which is maintained and tested):

https://github.com/zhiqwang/yolov5-rt-stack/blob/f4bb74ca14496883bf5252c9699864eba675f90d/.github/workflows/ci_test.yml#L93-L104

**Comment by zhiqwang** [comment]
Hmm, I think that what I answered above is a bit unrelated to your question, let me do some tests first.

**Comment by zhiqwang** [comment]
FYI. In order to prevent ambiguity, it is necessary to distinguish between the files under [CI](https://github.com/zhiqwang/yolov5-rt-stack/blob/f4bb74ca14496883bf5252c9699864eba675f90d/test/tracing/test_tracing.cpp) and [deployment](https://github.com/zhiqwang/yolov5-rt-stack/blob/f4bb74ca14496883bf5252c9699864eba675f90d/deployment/src/main.cpp).

torchvision 0.9.1 have refactored its interface, the CI is depend on torchvision 0.9.1, on the other side, deployment is depend on torchvision 0.8.2. And I only maintain the torchvision 0.9.1 now.

**Comment by stereomatchingkiss** [comment]
> 
> 
> Hmm, I think that what I answered above is a bit unrelated to your question, let me do some tests first.
> 
> Hi @stereomatchingkiss , As I mentioned above, the interface is a little outdated now, have you encountered any problems when compiling and testing the files under deployment?

Cannot compile it because I do not have torchvision for c++.
Looks like got a lot of jobs to do in order to make this work.

**Comment by zhiqwang** [comment]
You can check the [CI outputs](https://github.com/zhiqwang/yolov5-rt-stack/runs/2398463742?check_suite_focus=true#step:11:49) for more details, the type of the outputs is a list of dicts.

**Comment by zhiqwang** [comment]
Hi @stereomatchingkiss

We've added the codes to attach the `boxes`, `labels`, `scores` of the libtorch inferences results in 

I belive this can resolve your main doubt here, as such I'm closing this issue, and feel free to file a new issue if you have more questions.
